# Generated by Django 5.0.6 on 2025-09-04 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_perf_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='lead',
            name='lead_cat_idx',
        ),
        migrations.RemoveIndex(
            model_name='lead',
            name='lead_state_idx',
        ),
        migrations.RemoveIndex(
            model_name='lead',
            name='lead_city_idx',
        ),
        migrations.RemoveIndex(
            model_name='lead',
            name='lead_score_idx',
        ),
        migrations.RemoveIndex(
            model_name='lead',
            name='lead_biz_trgm',
        ),
        migrations.RemoveIndex(
            model_name='lead',
            name='lead_domain_trgm',
        ),
        migrations.RemoveIndex(
            model_name='lead',
            name='lead_email_trgm',
        ),
        migrations.AlterField(
            model_name='lead',
            name='domain',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='quality_score',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
