services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: leads
      POSTGRES_USER: leads
      POSTGRES_PASSWORD: leads
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    # Run via bash to avoid execute-bit issues on bind mounts
    command: ["/bin/bash", "-lc", "bash docker/entrypoint.sh"]

volumes:
  db_data:
